apps/post/urls.py
from django.conf.urls.defaults import *

from post.models import Post
from post.views import delete_post

urlpatterns = patterns('',
	url(r'^$', 'post.views.main_stream', name="main_stream"),
		
	url(r'^post/(?P<id>[0-9]+)/$', 'post.views.post', name="post"),
		url(r'^post/edit/(?P<id>[0-9]+)/$', 'post.views.edit_post', name="edit_post"),
		url(r'^post/delete/(?P<object_id>[0-9]+)/$', delete_post, name='delete_post'),
	
	url(r'^pin/(?P<id>[0-9]+)/$', 'post.views.pin', name="pin"),
	url(r'^unpin/(?P<id>[0-9]+)/$', 'post.views.unpin', name="unpin"),
	
	url(r'^task/add/(?P<id>[0-9]+)/$', 'post.views.add_task', name="add_task"),
	url(r'^task/remove/(?P<id>[0-9]+)/$', 'post.views.remove_task', name="remove_task"),
	url(r'^task/complete/(?P<id>[0-9]+)/$', 'post.views.complete_task', name="complete_task"),
	
	url(r'^todo/complete/(?P<id>[0-9]+)/$', 'post.views.complete_todo', name="complete_todo"),
	
	url(r'^filter/save/$', 'post.views.save_filter', name="save_filter"),
)

apps/project/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
	url(r'^(?P<project_id>[0-9]+)/$', 'project.views.project_stream', name="project"),
	url(r'^create/$', 'project.views.create_project', name="create_project"),
)

urls.py
from django.conf.urls.defaults import *
import settings

urlpatterns = patterns('',
	(r'^', include('post.urls')),
	(r'^user/', include('userprofile.urls')),
	(r'^project/', include('project.urls')),
)

if settings.LOCAL_DEVELOPMENT:
	urlpatterns += patterns('',
		url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
	)

apps/post/models.py
from django.db import models
from django.contrib.auth.models import User
from project.models import Project

import datetime

class Post(models.Model):
	posted_date = models.DateTimeField(default=datetime.datetime.now)
	updated = models.DateTimeField(auto_now=True)
	content = models.TextField()
	title = models.TextField()
	author = models.ForeignKey(User, related_name="posts")
	assigned = models.ManyToManyField(User, related_name="assigned_tasks", null=True)
	
	is_completed = models.BooleanField(default=False)
	completed_by = models.ForeignKey(User, related_name="completed_posts", null=True)
	
	project = models.ForeignKey(Project, null=True)
	
	has_files = models.BooleanField(default=False)
	has_todos = models.BooleanField(default=False)
	
	def comment_count(self):
		count = self.comment_set.count()
		if count == 0: return "no comments"
		if count == 1: return "%s comment" % count
		else:  return "%s comments" % count
		
	def last_comment(self):
		comments = self.comment_set.all()
		if len(comments) > 0:
			return self.comment_set.latest('posted_date')
		else: return None
	
	def __unicode__(self):
		return self.content
	
	class Meta:
		ordering = ['-updated']
		
class Comment(models.Model):
	posted_date = models.DateTimeField(default=datetime.datetime.now)
	post = models.ForeignKey(Post)
	comment = models.TextField()
	author = models.ForeignKey(User)
	
	class Meta:
		ordering = ['-posted_date']
	
class TodoItem(models.Model):
	posted_date = models.DateTimeField(default=datetime.datetime.now)
	post = models.ForeignKey(Post)
	content = models.TextField()
	is_completed = models.BooleanField()
	completed_by = models.ForeignKey(User, null=True)
	completed_date = models.DateTimeField(default=datetime.datetime.now)
	
	def __unicode__(self):
		return self.content
	
	class Meta:
		ordering = ['-posted_date']
	
class PostFile(models.Model):
	posted_date = models.DateTimeField(default=datetime.datetime.now)
	post = models.ForeignKey(Post)
	file = models.FileField(upload_to='post-files/%Y/%m/%d')
	
	def get_name(self):
		name = str(self.file).split('/')
		name.reverse()
		return name[0]
	
	class Meta:
		ordering = ['-posted_date']
		
class Filter(models.Model):
	owner = models.ForeignKey(User, related_name="filters")
	author_id = models.IntegerField(default=0)
	assigned_id = models.IntegerField(default=0)
	project_id= models.IntegerField(default=0)
	type = models.IntegerField(default=0)
	

apps/project/models.py
from django.db import models
from django.contrib.auth.models import User

class Project(models.Model):
	title = models.CharField(max_length=250)
	description = models.TextField()
	team = models.ManyToManyField(User)

apps/post/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from django.contrib.auth.models import User

from post.models import *
from userprofile.models import *
 
class PostForm(forms.ModelForm):
	assigned = forms.ModelMultipleChoiceField(queryset=User.objects.all(), required=False)
	class Meta:
		model = Post
		fields = ('content', 'title', 'assigned')
		
class TodoForm(forms.ModelForm):
	content = forms.CharField()
	class Meta:
		model = TodoItem
		fields = ('post', 'content')

class PostFileForm(forms.ModelForm):
	class Meta:
		model = PostFile
		exclude = ('posted_date')

class FilterForm(forms.ModelForm):
	assigned = forms.ModelMultipleChoiceField(queryset=User.objects.all(), required=False)
	class Meta:
		model = Filter
		
PostFileFormSet = inlineformset_factory(Post, PostFile, extra=1, form=PostFileForm, can_delete=False)
EditPostFileFormSet = inlineformset_factory(Post, PostFile, extra=1, form=PostFileForm)
TodoFormSet = inlineformset_factory(Post, TodoItem, extra=1, form=TodoForm, can_delete=False)
EditTodoFormSet = inlineformset_factory(Post, TodoItem, extra=1, form=TodoForm)

apps/project/forms.py
from django import forms
from project.models import *

class ProjectForm(forms.ModelForm):
	class Meta:
		model = Project
		exclude = ('team')

apps/post/views.py
from django.shortcuts import get_object_or_404, render_to_response, redirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from django.views.generic.create_update import delete_object
import datetime

from post.models import *
from userprofile.models import *
from project.models import *
from post.forms import *

# Methods

def add_post(request):
	if request.method == 'POST':
		form = PostForm(request.POST)
		if form.is_valid():
			p = form.save(commit=False)
			p.author_id = request.user.id;
			p.project_id = request.POST['project']
			p.save()
			p.assigned = form.cleaned_data['assigned']
			p.save()
			
			for u in form.cleaned_data['assigned']:
				try: u.email_user('River - '+p.title, p.content)
				except: pass
				Task(post=p, user=u, assigned_by=request.user).save()
			
			# Save files
			files = PostFileFormSet(request.POST, request.FILES, instance=p, prefix='files')
			files.save()
			
			# Save todo items
			todo = TodoFormSet(request.POST, instance=p, prefix='todos')
			todo.save()
			
			if p.todoitem_set.count() > 0: p.has_todos = True
			if p.postfile_set.count() > 0: p.has_files = True
			p.save()
			
			request.user.message_set.create(message="Posted Added!")
			
			# Notify the right people 
			for u in UserProfile.objects.filter(last_active__lt=(p.posted_date - timedelta(minutes=3))):
				u.notifications.add(p)
		else:
			raise Exception
			
# Views
		
@login_required
def main_stream(request):
	add_post(request)
	return render_to_response("posts/main.html", {
		'projects':Project.objects.all(),
		'users':User.objects.all(),
		'request':request,
	}, context_instance=RequestContext(request))

@login_required
def edit_post(request, id):
	if request.method == 'POST': # and request.POST['content'] and request.POST['title']:
		p = Post.objects.get(id=id)
		if request.user == p.author:
			form = PostForm(request.POST, instance=p)
			if form.is_valid:
				p = form.save()
				
				# Save files
				files = EditPostFileFormSet(request.POST, request.FILES, instance=p, prefix='files')
				files.save()
				
				# Save todo items
				todo = EditTodoFormSet(request.POST, instance=p, prefix='todos')
				todo.save()
				
				# p.content = request.POST['content']
				# p.title = request.POST['title']
				# p.save()
				request.user.message_set.create(message="Posted Edited!")
	return redirect('/post/'+id)
	
@user_passes_test(lambda u: u.is_superuser, login_url='/')
def delete_post(request, object_id):
    return delete_object(request, Post, '/', object_id=object_id, template_name='admin/delete_confirm.html')

@login_required
def post(request, id):
	post = Post.objects.get(id=id)

	if request.method == 'POST' and request.POST['comment']:
		Comment(comment=request.POST['comment'], post=post, author=request.user).save()
		post.save()

	return render_to_response("posts/post.html", {
		'post':post,
		'request':request,
		'file_formset': EditPostFileFormSet(prefix='files', instance=post),
		'todo_formset': EditTodoFormSet(prefix='todos', instance=post),
		'form': PostForm(instance=post),
		'users': User.objects.all(),
	}, context_instance=RequestContext(request))
	
# Quick Actions

@login_required
def save_filter(request):
	if request.method == "POST":
		form = FilterForm(request.POST)
		if form.is_valid():
			f = form.save(commit=False);
			f.id = request.user.get_profile().get_filter().id
			f.save()
		else:
			raise Exception
	return redirect('/') if not request.GET.__contains__('next') else redirect(request.GET['next'])

@login_required
def complete_todo(request, id):
	t = TodoItem.objects.get(id=id)
	if not t.is_completed:
		t.is_completed = True
		t.completed_by = request.user
		t.completed_date = datetime.now()
	else:
		t.is_completed = False
	t.save()
	return redirect('/') if not request.GET.__contains__('next') else redirect(request.GET['next'])
	
@login_required
def pin(request, id):
	try:
		request.user.get_profile().board.add(id)
		request.user.message_set.create(message="Post Pined!")
	except: pass
	return redirect('/') if not request.GET.__contains__('next') else redirect(request.GET['next'])
	
@login_required
def unpin(request, id):
	request.user.get_profile().board.remove(id)
	request.user.message_set.create(message="Posted Unpined!")
	return redirect('/user/board') if not request.GET.__contains__('next') else redirect(request.GET['next'])
	
@login_required
def add_task(request, id):
	p = Post.objects.get(id=id)
	Task(post=p, user=request.user).save()
	request.user.message_set.create(message="Task Added!")
	return redirect('/') if not request.GET.__contains__('next') else redirect(request.GET['next'])
	
@login_required
def remove_task(request, id):
	Task.objects.get(post=Post.objects.get(id=id), user=request.user).delete()
	request.user.message_set.create(message="Task Removed!")
	return redirect('/') if not request.GET.__contains__('next') else redirect(request.GET['next'])
	
@login_required
def complete_task(request, id):
	t = Task.objects.get(id=id)
	if t.is_completed: 
		t.is_completed = False
		if t.assigned_by:
			t.post.is_completed = False
			t.post.save()
	else: 
		t.is_completed = True
		if t.assigned_by:
			t.post.is_completed = True
			t.post.save()
	t.save()
	request.user.message_set.create(message="Task Completed!")
	return redirect('user_tasks') if not request.GET.__contains__('next') else redirect(request.GET['next'])

apps/project/views.py
from django.shortcuts import get_object_or_404, render_to_response, redirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from post.models import *
from post.forms import *
from post.views import add_post
from project.models import *
from project.forms import *

@login_required
def create_project(request):
	if request.method == "POST":
		form = ProjectForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/')
	else: form = ProjectForm()
	return render_to_response("project/create.html", {
		'form':form
	}, context_instance=RequestContext(request))

@login_required
def project_stream(request, project_id):
	add_post(request)
		
	return render_to_response("posts/project.html", {
		'project':Project.objects.get(id=project_id),
		'request':request,
	}, context_instance=RequestContext(request))

templates/posts/main.html
{% extends "base.html" %}
{% load post_tags %}

{% block content %}
<div class='nav'>
	<a href="/">Main Stream</a> | <a href="/user/board/">Board</a> | <a href="/user/tasks/">Tasks</a>
</div>
	<div class="filter">

		<form method="POST" action='{% url save_filter %}'>
		Showing 
		<select name="type">
			<option value="0">Everything</option>
			<option value="1"{% ifequal user.get_profile.get_filter.type 1 %}
				selected="selected"
			{% endifequal %}>Todo Lists</option>
			<option value="2" {% ifequal user.get_profile.get_filter.type 2 %}
				selected="selected"
			{% endifequal %}>Files</option>
		</select>
		in
		<select name="project_id">
			<option value="0">All Projects</option>
			{% for p in projects %}
				<option {% ifequal user.get_profile.get_filter.project_id p.id %}
					selected="selected"
				{% endifequal %}value="{{p.id}}">{{p.title}}</option>
			{% endfor %}
		</select>
		assigned to
		<select name="assigned_id">
			<option value="0">Anyone</option>
			{% for u in users  %}
				<option {% ifequal user.get_profile.get_filter.assigned_id u.id %}
					selected="selected"
				{% endifequal %} value="{{u.id}}">{{u.get_profile.get_name}}</option>
			{% endfor %}
		</select>
		and posted by
		<select name="author_id">
			<option value="0">Anyone</option>
			{% for u in users  %}
				<option {% ifequal user.get_profile.get_filter.author_id u.id %}
					selected="selected"
				{% endifequal %} value="{{u.id}}">{{u.get_profile.get_name}}</option>
			{% endfor %}
		</select>
		<input type="hidden" name="owner" value="{{user.id}}" id="owner">
		<input type="submit" value="Filter" />
		</form>
	</div>
	{% poster %}
	{% post_stream request %}
{% endblock %}

templates/posts/post.html
{% extends "base.html" %}
{% load markup %}
{% load post_tags %}
{% load post_filters %}

{% block js %}
	<script src="/media/js/avts.edit.js" type="text/javascript" charset="utf-8"></script>
	<script src="/media/js/avts.edit_post.js" type="text/javascript" charset="utf-8"></script>
	<script src="/media/js/avts.clonemore.js" type="text/javascript" charset="utf-8"></script>
	<script src="/media/js/avts.attachments.js" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% block content %}	
	<div id="stream" class="full_width">
		
		{% load markup %}
		{% load post_filters %}
		{% load post_tags %}

		<div class='item no_shadow'>
			<div class='item_content'>
				<h1 class="title">
					<a href="{% url post post.id %}">{{post.title}}</a>
					<a href="#" class='post_project_name'>
						{% if post.project %}
							{{post.project}}
						{% else %}
							Main Stream
						{% endif %}

					</a>
				</h1>

				{% if post.todoitem_set.all %}
					<div class='todo_list'>
						{% for todo in post.todoitem_set.all %}
							{% if not todo.is_completed %}
								<p><input type='checkbox' class='inline_todo' value='{{todo.id}}'> {{todo.content}}</p>
							{% else %}
								<p><input type='checkbox' checked='checked' disabled='disabled'> {{todo.content}} <i>completed by {{todo.completed_by.get_profile.get_name}} {{todo.completed_date|timesince}} ago</i></p>
							{% endif %}
						{% endfor %}
					</div>
				{% endif %}

				{{post.content|urlize|textile}}

				{% if post.postfile_set.all %}
				<div class="files">
					{% for f in post.postfile_set.all %}
						<a href="/media/{{f.file}}" target="_blank">{{f.get_name}}</a><br/>
					{% endfor %}
				</div>

				{% endif %}

			</div>

			{% ifequal user post.author  %}
				<form class="edit_form hide" method="post" action="{% url edit_post post.id %}" enctype="multipart/form-data">
					<div class='edit_header'>
						Editing: {{post.title}}
					</div>
					{{file_formset.management_form}}
					{{todo_formset.management_form}}
					<label>Title</label> <input name='title' class='text' value="{{post.title}}">
					<label>Content</label> <textarea name='content'>{{post.content}}</textarea>
					<label>Attachments</label>
					<div class='edit_attachments'>
						<h1><a href="#" class="add_poster_file">Attach File</a> | <a href="#" class="assign_poster">Assign</a> | <a href="#" class="add_poster_todo">Add Todo Item</a></h1>
						<div class="attachemnts">
							{% for form in file_formset.forms %}
								<p>
									<a href="#" class='delete_soft_item_edit'></a>
									{% if form.instance.file %}
										<a href="/media/{{form.instance.file}}">Current File</a> |
									{% endif %}
									{% for f in form %}
										{{f}}
									{% endfor %}
								</p>
							{% endfor %}
						</div>
						
						<div class='todos'>
							{% for form in todo_formset.forms %}
								<p class='todo_edit'>
									<a href="#" class='delete_soft_item_edit'></a>
									{% for f in form %}
										{{f}}
									{% endfor %}
								</p>
							{% endfor %}
						</div>
						
						<div class="assigner">
							<select multiple="multiple" name="assigned" id="id_assigned">
								{% for u in users %}
									<option value="{{u.id}}">{{u.get_profile.get_name}}</option>
								{% endfor %}
							</select>
						</div>
					</div>
					
					<div class='edit_footer'>
						<input type="submit" value="Save Changes"> <a href="{% url post post.id %}">Nevermind</a>
					</div>
				</form>
			{% endifequal %}

			<div class='comment_div'>
				<div class='comments'>
					{% for comment in post.comment_set.all %}
						{% comment comment %}
					{% empty %}
						<div class='comment last'>
							There are no comments yet.
						</div>
					{% endfor %}
				</div>

				<form method="post" class='add_comment' id="comments">
					<textarea class='autosize' name='comment'></textarea>
					<input type='submit' value='Add Comment' />
				</form>
			</div>

			<div class='info'>
				Posted by <a class='highlight' href="">{{post.author.get_profile.get_name}}</a> {{post.posted_date|timesince}} ago
				{% if post.project %}
					in <a href="{% url project post.project.id %}">{{post.project.title}}</a>
				{% endif %} with <a href="{% url post post.id %}#comments">{{post.comment_count}}</a>
				{% if post.assigned.all %}
					assigned to 
					{% ifequal post.assigned.all|length 1 %}
						{% for u in post.assigned.all %}{{u.get_profile.get_name}}{% endfor %}
					{% else %}
						{{post.assigned.all|length}} people
					{% endifequal %}
				{% endif %}
				{% if post.is_completed %}
					| Completed
				{% endif %}
				<span class='controls'>
					{% if user|ispined:post %}<a class='left' href="{% url unpin post.id %}?next={{request.path}}">Unpin</a>{% else %}<a class='left' href="{% url pin post.id %}?next={{request.path}}">Pin to board</a>{% endif %}
					 | {% if user|istask:post %}<a class='right' href="{% url remove_task post.id %}?next={{request.path}}">Remove from tasks</a>{% else %}<a class='right' href="{% url add_task post.id %}?next={{request.path}}">Add to tasks</a>{% endif %}
					{% ifequal user post.author %}
						| <a href="#" class='edit_post_link'>Edit</a>
					{% endifequal %}
				</span>
			</div>
			
		</div>
		
	</div>
	</div>
{% endblock %}

templates/posts/project.html
{% extends "base.html" %}
{% load post_tags %}

{% block content %}
	{% poster project.id %}
	<span class='project_items'>
	{% post_stream request project.id %}
	</span>
	<div class="project_info">
		<span class="description">
			<h1>{{project.title}}</h1>
			<p>This is were the project description would go. It would give a short description of what the project is about and some ore stuff that I can't think of right now because its 12:01 and I'm typing too fast. I don't like to use lorum lipsum obviously</p>
			<p>All I would have to do is alt-tab and type lipsum.com and then I would just copy some text but that wouldn't be nearly as fun</p>
		</span>
		
		<div class='messages list'>
			<h2>Messages</h2>
			<ul>
				{% for p in project.post_set.all %}
					<li><a href="{% url post p.id %}">{{p.title}}</a> <span class='info'>Lasted updated {{p.updated|timesince}}</span></li>
				{% endfor %}
			</ul>
		</div>
		
		<div class='files list'>
			<h2>Files (Demo)</h2>
			<ul>
				<li>Intro-to-git.pdf</li>
				<li>screenshot.png</li>
				<li>logo.jpg</li>
			</ul>
		</div>
	</div>
{% endblock %}