urls.py
from django.conf.urls.defaults import *
import settings

urlpatterns = patterns('',
	(r'^', include('post.urls')),
	(r'^user/', include('userprofile.urls')),
	(r'^project/', include('project.urls')),
)

if settings.LOCAL_DEVELOPMENT:
	urlpatterns += patterns('',
		url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
	)

apps/post/models.py
from django.db import models
from django.contrib.auth.models import User
from project.models import Project

import datetime

class Post(models.Model):
	posted_date = models.DateTimeField(default=datetime.datetime.now)
	updated = models.DateTimeField(auto_now=True)
	content = models.TextField()
	title = models.TextField()
	author = models.ForeignKey(User, related_name="posts")
	assigned = models.ManyToManyField(User, related_name="assigned_tasks", null=True)
	
	is_completed = models.BooleanField(default=False)
	completed_by = models.ForeignKey(User, related_name="completed_posts", null=True)
	
	project = models.ForeignKey(Project, null=True)
	
	has_files = models.BooleanField(default=False)
	has_todos = models.BooleanField(default=False)
	
	def comment_count(self):
		count = self.comment_set.count()
		if count == 0: return "no comments"
		if count == 1: return "%s comment" % count
		else:  return "%s comments" % count
		
	def last_comment(self):
		comments = self.comment_set.all()
		if len(comments) > 0:
			return self.comment_set.latest('posted_date')
		else: return None
	
	def __unicode__(self):
		return self.content
	
	class Meta:
		ordering = ['-updated']
		
class Comment(models.Model):
	posted_date = models.DateTimeField(default=datetime.datetime.now)
	post = models.ForeignKey(Post)
	comment = models.TextField()
	author = models.ForeignKey(User)
	
	class Meta:
		ordering = ['-posted_date']
	
class TodoItem(models.Model):
	posted_date = models.DateTimeField(default=datetime.datetime.now)
	post = models.ForeignKey(Post)
	content = models.TextField()
	is_completed = models.BooleanField()
	completed_by = models.ForeignKey(User, null=True)
	completed_date = models.DateTimeField(default=datetime.datetime.now)
	
	def __unicode__(self):
		return self.content
	
	class Meta:
		ordering = ['-posted_date']
	
class PostFile(models.Model):
	posted_date = models.DateTimeField(default=datetime.datetime.now)
	post = models.ForeignKey(Post)
	file = models.FileField(upload_to='post-files/%Y/%m/%d')
	
	def get_name(self):
		name = str(self.file).split('/')
		name.reverse()
		return name[0]
	
	class Meta:
		ordering = ['-posted_date']
		
class Filter(models.Model):
	owner = models.ForeignKey(User, related_name="filters")
	author_id = models.IntegerField(default=0)
	assigned_id = models.IntegerField(default=0)
	project_id= models.IntegerField(default=0)
	type = models.IntegerField(default=0)
	

apps/post/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from django.contrib.auth.models import User

from post.models import *
from userprofile.models import *
 
class PostForm(forms.ModelForm):
	assigned = forms.ModelMultipleChoiceField(queryset=User.objects.all(), required=False)
	class Meta:
		model = Post
		fields = ('content', 'title', 'assigned')
		
class TodoForm(forms.ModelForm):
	content = forms.CharField()
	class Meta:
		model = TodoItem
		fields = ('post', 'content')

class PostFileForm(forms.ModelForm):
	class Meta:
		model = PostFile
		exclude = ('posted_date')

class FilterForm(forms.ModelForm):
	assigned = forms.ModelMultipleChoiceField(queryset=User.objects.all(), required=False)
	class Meta:
		model = Filter
		
PostFileFormSet = inlineformset_factory(Post, PostFile, extra=1, form=PostFileForm, can_delete=False)
EditPostFileFormSet = inlineformset_factory(Post, PostFile, extra=1, form=PostFileForm)
TodoFormSet = inlineformset_factory(Post, TodoItem, extra=1, form=TodoForm, can_delete=False)
EditTodoFormSet = inlineformset_factory(Post, TodoItem, extra=1, form=TodoForm)

templates/stream/partials/comment.html
{% load markup %}

<div class='comment'>
	<div class="comment_info">
		{{comment.author.get_profile.get_name}} <span class='posted'>{{comment.posted_date|timesince}} ago</span>
	</div>
	{{comment.comment|linebreaksbr|urlize|textile}}

</div>

templates/stream/partials/poster.html
<script src="/media/js/avts.clonemore.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" charset="utf-8">
	$(function(){
		var attachments_hidden = true;
		var todos_hidden = true;
		
		//$("select#id_assigned").hide();
		$('div.assigner').hide();
		$('div.todos').hide();
		$('div.attachemnts').hide();
		
		$("a.assign_poster").click(function(e){
			e.preventDefault();
			$(".assigner").toggle();
		});
		
		$('a.add_poster_file').click(function(e){
			e.preventDefault();
			if (attachments_hidden) {
				$('div.attachemnts').show();
				attachments_hidden = false;
				return;
			}
			cloneMore('div.attachemnts p:last', 'files');
		});
		
		$('a.add_poster_todo').click(function(e){
			e.preventDefault();
			if (todos_hidden) {
				$('div.todos').show();
				todos_hidden = false;
				return;
			}
			cloneMore('div.todos p:last', 'todos');
		});
		
		$('a.delete_soft_item').click(function(e){
			e.preventDefault();
			// Make sure we don't delete the last one
			if ($(this).parent('p').parent('div').children('p').length > 1) $(this).parent('p').remove();
			else {
				$(this).parent('p').parent('div').hide();
				if ($(this).parent('p').parent('div').attr('class') == 'todos') todos_hidden = true;
				if ($(this).parent('p').parent('div').attr('class') == 'attachemnts') attachments_hidden = true;
			}
		});
	});
</script>

<div id="poster">
	<form method="post" id="main_poster" enctype="multipart/form-data">
		{{file_formset.management_form}}
		{{todo_formset.management_form}}
		<div class="inputs poster_footer">
			<input name="title" id="poster_title">
			<textarea name="content" class='autosize post_text' id="poster_textarea">Type your message here...</textarea>
			<div class="assigner">
				<select multiple="multiple" name="assigned" id="id_assigned">
					{% for u in users %}
						<option value="{{u.id}}">{{u.get_profile.get_name}}</option>
					{% endfor %}
				</select> <a href='#' class='assign_poster'>Hide</a>
			</div>
			<div class="attachemnts">
				{% for form in file_formset.forms %}
					<p>
						<a href="#" class='delete_soft_item'>Delete</a> |
						{% for f in form %}{{f}}{% endfor %}
					</p>
				{% endfor %}
			</div>
			<div class='todos'>
				{% for form in todo_formset.forms %}
					<p>
						<a href="#" class='delete_soft_item'>Delete</a> |
						{% for f in form %}{{f}}{% endfor %}
					</p>
				{% endfor %}
			</div>
			<div class="controls">
				<input class='post_button' type="submit" value="" id="Add" /> <span class='between'>in</span>
				<select name="project">
					<option value="0">Main Stream</option>
					{% for p in projects %}
						{% ifequal p.id project_id  %}
							<option selected='true' value="{{p.id}}">{{p.title}}</option>
						{% else %}
							<option value="{{p.id}}">{{p.title}}</option>
						{% endifequal %}
					{% endfor %}
				</select> 
				<div class='extras'>
				<a href="#" class="add_poster_file"><img src="/media/imgs/attach-button.png" width="70" height="31" alt="Attach Button"></a> <a href="#" class="assign_poster"><img src="/media/imgs/assign-button.png" width="72" height="31" alt="Assign Button"></a> <a href="#" class="add_poster_todo"><img src="/media/imgs/add-todo-button.png" width="91" height="32" alt="Add Todo Button"></a>
				</div>
			</div>
		</div>
	</form>
</div>

templates/stream/partials/stream.html
<div id="stream"{% if not project_id %} class='full_width'{% endif %}>
	{% if notifications %}		
		<div id="notifications">
			{{notifications|length}} New Posts:
			{% for n in notifications %}
				<a href="{% url post n.id %}">{{n.title}}</a>{% if not forloop.last %}, {% endif %}
			{% endfor %}
		</div>
	{% endif %}
	
	<span class='items'>
	{% for s in stream %}
		{% ifchanged s.posted_date.day %}
			</span>
			</div>
			
			<div class='day_div'>
				<h2 class='day_title'>{{s.posted_date|date:"l d M"}}</h2>
			</div>
			
			<div id="stream"{% if not project_id %} class='full_width'{% endif %}>
			<span class='items'>
		{% endifchanged %}
		{% include "stream/partials/stream_item.html" %}
	{% endfor %}
	</span>
</div>

templates/stream/partials/stream_item.html
{% load markup %}
{% load post_filters %}
{% load post_tags %}

<div class='item{% cycle '' ' odd' %}'>
	<div class='item_content'>
		<h1 class="title"><a href="{% url post s.id %}">{{s.title}}</a></h1>
	
		{% if s.todoitem_set.all %}
			<div class='todo_list'>
				{% for todo in s.todoitem_set.all %}
					{% if not todo.is_completed %}
						<p>{{todo.content}} | <a href="{% url complete_todo todo.id %}">Complete</a></p>
					{% else %}
						<p>{{todo.content}} | completed by {{todo.completed_by.get_profile.get_name}} {{todo.completed_date|timesince}} ago</p>
					{% endif %}
				{% endfor %}
			</div>
		{% endif %}
	
		{{s.content|urlize|textile}}
	
		{% if s.postfile_set.all %}
		<div class="files">
			<h2>Files</h2>
			{% for f in s.postfile_set.all %}
				<a href="/media/{{f.file}}" target="_blank">{{f.get_name}}</a><br/>
			{% endfor %}
		</div>

		{% endif %}
	
	</div>
	
	{% ifnotequal s.posted_date|date:"d/m/Y/H:i:s" s.updated|date:"d/m/Y/H:i:s"  %}
		{# {% if s.last_comment %} #}
		{# 	<div class='latest_comment'> #}
		{# 		{% comment s.last_comment %} #}
		{# 	</div> #}
		{# {% endif %} #}
	{% endifnotequal %}
	
	<div class='info'>
		Posted by <a class='highlight' href="#">{{s.author.get_profile.get_name}}</a> {{s.posted_date|timesince}} ago
		{% if s.project %}
			in <a href="{% url project s.project.id %}">{{s.project.title}}</a>
		{% endif %} | <a href="{% url post s.id %}">View this post</a> | <a href="{% url post s.id %}#comments">{{s.comment_count}}</a>
		{% if s.assigned.all %}
			Assigned to {% for u in s.assigned.all %}{{u.get_profile.get_name}}{% endfor %}
		{% endif %}
		{% if s.is_completed %}
			| Completed
		{% endif %}
	</div>
	
	<ul class='controls'>
		
		<li class="board">
			{% if user|ispined:s %}
			<a class='left' href="{% url unpin s.id %}?next={{request.path}}">Unpin</a>
			{% else %}
			<a class='left' href="{% url pin s.id %}?next={{request.path}}">Pin to board</a>
			{% endif %}
		</li>
		
		<li class="task">
			{% if user|istask:s %}
			<a class='right' href="{% url remove_task s.id %}?next={{request.path}}">Remove from tasks</a>
			{% else %}
			<a class='right' href="{% url add_task s.id %}?next={{request.path}}">Add to tasks</a>
			{% endif %}
		</li>
		
	</ul>
	
	
</div>